### ISSUE TITLE
Debugar requisições com reposta de erro

### ISSUE THREAD

**Issue by leomp12** [ecomclub/app-bling#10]
Os logs atuais não são tão conclusivos, por exemplo:

```console
{ Error: Erro no callback de estoque para #1094
    at bling.produtos.getById.then.then.then.catch.error (/var/nodejs/bling/lib/bling/handle-callback.js:69:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  original:
   '{"retorno":{"erros":{"erro":{"cod":3,"msg":"API Key invalida"}}}}' }
```

Não evidencia a requisição que foi feita, acho importante termos neste log pelo menos o URL e cabeçalho das requisições que fralharem pra termos certeza que a requisição está conforme a documentação do Bling e configurações do lojista.

> Mas sem flodar os arquivos de log com objetos circulares de request/response.

**Comment by talissonf** [comment]
Eu passei a usar o axios, os logs vão seguir o padrão dos outros.
