### ISSUE TITLE
Salvar erros da integração na Store API

### ISSUE THREAD

**Issue by leomp12** [ecomclub/app-bling#11]
Em integrações mais complexas precisamos permitir que o lojista visualize erros decorrentes de configuração incorreta pra agilizar a solução e reduzir demanda de suporte, por isto é importante que o lojista possa ver as respostas de erro retornadas pela API do Bling, e para isto precisamos salvar os erros no objeto do aplicativo na Store API e depois exibir este log na [view do aplicativo](https://github.com/ecomplus/admin-marketplace/blob/master/src/views/apps/AppBling.vue).

> Na verdade eu achei que isto já estava sendo feito (ouvi ou vi isto em algum momento), mas aparentemente não está, ou está @talissonf ?

**Comment by talissonf** [comment]
Os logs sempre foram salvos, mas no hidden_data do app. Quando eu fiz a view eu até pensei em exibir mas achei que podia pesar um pouco e acabei deixando de lado.

**Comment by leomp12** [comment]
Hmm, então já estão sendo salvos corretamente? Talvez eu comi mosca então.
Mas precisamos exibir na view sim, se der pro lojista deletar entradas manualmente melhor ainda.
