### ISSUE TITLE
Permitir envio de pedidos antes da aprovação

### ISSUE THREAD

**Issue by matheusgnreis** [ecomclub/app-bling#12]
No caso de enviar tanto aprovado quanto aguardando pagamento, se for escolhida essa opção, atualizamos o status dele, se for aprovado ou cancelado. Isso porque, existem casos que querem jogar apenas pedidos aprovados para o Bling, agora existem outros casos que se o pedido fica aguardando pagamento na e-com e não é enviado a informação de estoque para o bling, e o produto é vendido em algum marketplace, depois esse pedido na e-com fica aprovado, nesse caso, o lojista pode ter um problema de estoque.

**Comment by matheusgnreis** [comment]
Já ouvi dizer que têm um aprisionamento de estoque, não sei ao certo, acredito que assim funcionaria também, mas não sei ao certo. A primeira seria mais formalizada

**Comment by leomp12** [comment]
@talissonf ou seja, precisamos de um booleano _Enviar pedidos em aberto_ na configuração que ative o envio de pedidos com financial status `pending` `under_analysis`, `authorized` OU `paid` (qualquer status não cancelado), a partir daí todo status deverá ser sincronizado.

A priori é uma alteração simples, só mexer onde você recebe o webhook de orders e alterar a verificação de status, talvez seja problema apenas a sincronização de status (qualquer status) depois disto, dependendo da sua implementação atual...

**Comment by talissonf** [comment]
👍🏼

**Comment by talissonf** [comment]
https://github.com/ecomplus/app-bling/commit/fec14528f5e045dc46c8c85710e072b93126f355
