### ISSUE TITLE
Configuração padrão do app

### ISSUE THREAD

**Issue by leomp12** [ecomclub/app-bling#15]
Por padrão apenas as seguintes automações devem estar ativas:
- envio automático de pedidos da plataforma para o ERP;
- atualização de status dos pedidos enviados da plataforma para o ERP;
- atualização de estoque do ERP para a plataforma;

Este é o caso mais comum e mais simples, outras automações devem ser desativadas por padrão, exigindo que o lojista ative no painel.

O envio de produtos da plataforma para o ERP em geral é feito manualmente, não deve ser automático por padrão pra evitar que os produtos sejam duplicados no ERP sem querer (na maioria das vezes os produtos já estão no ERP quando o lojista começa a utilizar a plataforma).

**Comment by leomp12** [comment]
Boa noite @talissonf ,

Vi seu joinha mas o issue tá aberto ainda, você já desembolou isso aqui? Se não tiver feito ainda dá uma priorizada nesse issue e o outro do Bling aqui por favor.

Isso é bem importante porque já deu uma cagadinha com uma loja e dependendo da operação pode dar uma cagada bem grande, e o cara só vai ver depois de feito...

**Comment by leomp12** [comment]
@matheusgnreis na verdade parece que a exportação de produtos nunca foi automática, eu não sei se lembro bem, o que aconteceu foi que os produtos foram enviados mesmo sem o lojista querer? Tem certeza que ele não enviou manualmente? Tentou replicar o problema?
@talissonf esta exportação é só adicionando os IDs um a um?

**Comment by talissonf** [comment]
Skus separados por `,` vírgula

**Comment by matheusgnreis** [comment]
O lojista informou que não viu a descrição de envio de produtos e ativou tudo, depois ele pediu desculpa, pois ficou nervoso com a situação em que se meteu sem querer
