### ISSUE TITLE
Imagens de produtos importados sem conexão segura (HTTPS)

### ISSUE THREAD

**Issue by leomp12** [ecomclub/app-bling#19]
Produtos importados estão sendo salvos com o `url` nas `pictures` com conexão http em vez de https, pelo que vi são sempre links da AWS S3, suportam HTTPS normalmente e deveriam ser salvos desta forma para evitar conteúdo misto no storefront.

**Comment by leomp12** [comment]
Na verdade o ideal mesmo era fazer o upload das imagens via Storage API: https://gist.github.com/leomp12/1f69523cbf8fb1c9a27e513697309719
Pra salvá-las em WebP e um formato fallback e com as devidas variações de tamanho.
> Aqui já não é um bug, um enhancement, pode ser trabalhoso e deixado pra depois por enquanto, mas seria o mais correto.

**Comment by matheusgnreis** [comment]
Isso é importante porque as imagens do bling que são buscadas via API possui um tempo de validade, logo após um período x, as imagens param de funcionar.

**Comment by talissonf** [comment]
> logo após um período x, as imagens param de funcionar.

wtf?

Mas devo mexer no bling na semana q vem e bico isso

**Comment by leomp12** [comment]
Ah é por isso que direto aparecia um produto com imagem quebrada na 1011 então :neutral_face: 
Ideia de girico do Bling em

**Comment by leomp12** [comment]
Um exemplo disso aqui pra adiantar https://github.com/ecomplus/app-ideris/blob/e805da28da2263df9841dd51e56b0f42d552be48/functions/lib/integration/parsers/product-to-ecomplus.js#L12-L63
