### ISSUE TITLE
Erro Importação de produtos com variação do Bling para E-Com

### ISSUE THREAD

**Issue by matheusgnreis** [ecomclub/app-bling#26]
A loja 1154 tentou fazer a importação dos produtos do Bling para a E-Com, porém vieram somente os produtos, mas sem as variações, no log temos por exemplo:

```
{
    "error": "Cannot read property 'trim' of undefined",
    "storeId": 1154,
    "product_sku": "001505"
}
```

**Comment by talissonf** [comment]
Eu verifiquei os produtos dela, e o cadastro deles no bling não seguem o padrão definido pelo bling https://ajuda.bling.com.br/hc/pt-br/articles/360035987033
