### ISSUE TITLE
Store ID erro de inserção admin marketplace

### ISSUE THREAD

**Issue by matheusgnreis** [ecomclub/app-bling#7]
Ao tentar configurar em admin marketplace o store id do Bling, como é um número muito grande e está configurado como um inteiro, então ao inseri-lo está jogando para 9999999. De acordo com Leo, pelo tamanho do número tem que ser considerado com uma string

**Comment by leomp12** [comment]
@talissonf isto é bem importante, tá entre as correções que você fez nestes últimos releases?

**Comment by talissonf** [comment]
Eu corrigi, na verdade acho o Matheus tá falando do campo loja id do Bling no admin marketplace. Eu arrumei o schema do admin settings dele já.

**Comment by talissonf** [comment]
Instalações antigas tem que fazer patch pra atualizar isso

**Comment by leomp12** [comment]
É isso, no admin marketplace mesmo, mas se alterou no admin settings lá deve funcionar também (como input text).
Valeu!
