### ISSUE TITLE
Alterar status de pedidos existentes no bling

### ISSUE THREAD

**Issue by talissonf** [ecomclub/app-bling#8]
Pedidos enviados para o bling com status de aprovados deveram ser cancelados no bling caso sejam cancelados na plataforma.

**Comment by leomp12** [comment]
@talissonf acho que te falei que poderíamos deixar isto pra depois, mas como o estoque não está sendo atualizado automaticamente da plataforma para o Bling, esta feature se tornou essencial pro controle de estoque (que é o mais importante), faz sentido?

Uma das duas coisas precisa estar funcionando logo na primeira versão, até acho que é mais simples manter a sincronização de estoque em uma via só, mas neste caso o Bling precisa estar sempre com os pedidos atualizados, se não o estoque vai embolar.

**Comment by talissonf** [comment]
Pronto, agora o pedido é cancelado no bling caso seja enviado para la e depois cancelado na plataforma. https://github.com/ecomplus/app-bling/commit/694c08c8212be12c96ce59a0bf4156cd0b367ca5
